In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("test.csv")

In [6]:
df

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,50785,0.0,2013-02-04,548.0,1996,2204.0,35.290799,-4.059696e+00,22264,0,...,5,0,0,3,3,6,4,2,3,3
1,51630,0.0,2013-02-04,952.0,1569,2396.0,36.656709,-3.309214e+00,926,0,...,5,0,0,1,1,1,1,1,1,1
2,17168,0.0,2013-02-01,NaN,1567,NaN,34.767863,-5.004344e+00,10761,0,...,5,0,0,1,1,6,4,2,3,3
3,45559,0.0,2013-01-22,1818.0,267,1477.0,38.058046,-9.418672e+00,33286,0,...,3,0,0,0,0,4,2,1,3,3
4,49871,500.0,2013-03-27,1658.0,1260,2052.0,35.006123,-1.095041e+01,25929,0,...,2,0,0,2,2,1,1,1,1,1
5,52449,0.0,2013-03-04,952.0,1685,2396.0,36.685279,-3.302420e+00,34449,0,...,5,0,0,2,2,1,1,1,1,1
6,24806,0.0,2011-03-02,952.0,550,1770.0,36.398041,-7.541382e+00,18590,0,...,5,5,3,2,2,2,6,1,0,0
7,28965,0.0,2013-01-25,1503.0,234,444.0,39.607420,-1.089379e+01,16087,0,...,5,0,0,0,0,2,6,1,4,1
8,36301,30.0,2013-01-23,655.0,584,1525.0,39.262951,-1.082359e+01,1391,0,...,1,0,0,1,1,1,1,1,1,1
9,54122,0.0,2013-03-18,361.0,1083,1993.0,37.096108,-3.251754e+00,40157,0,...,2,0,0,2,2,1,1,1,1,1
10,419,5.0,2013-10-03,1978.0,1259,18.0,37.233248,-3.241121e+00,44625,0,...,1,0,0,2,2,1,1,1,1,1
11,45750,0.0,2013-02-27,1624.0,608,1565.0,37.686392,-4.555975e+00,36315,0,...,5,0,0,0,0,6,4,2,3,3
12,653,0.0,2012-10-11,1295.0,0,534.0,33.661074,-4.165720e+00,710,0,...,3,0,0,0,0,2,6,1,4,1
13,14017,0.0,2011-07-29,53.0,0,2396.0,33.007680,-3.209529e+00,22278,0,...,1,0,0,2,2,2,6,1,4,1
14,44607,1000.0,2011-03-02,842.0,1625,1417.0,35.615624,-7.870290e+00,18590,0,...,2,0,0,2,2,1,1,1,1,1
15,40228,1200.0,2013-06-03,842.0,916,2396.0,35.482886,-1.091260e+01,18988,0,...,4,0,0,2,2,8,0,2,4,1
16,27714,0.0,2011-02-24,NaN,-39,NaN,39.850190,-7.727946e+00,16236,0,...,5,0,0,2,2,4,2,1,0,0
17,28785,200.0,2011-03-11,952.0,1793,2396.0,38.254024,-4.565802e+00,35055,0,...,2,0,0,2,2,1,1,1,1,1
18,28330,0.0,2012-10-06,2085.0,0,2396.0,31.586798,-3.387808e+00,37954,0,...,3,0,0,3,3,6,4,2,1,1
19,18532,0.0,2013-02-02,1503.0,368,444.0,39.438526,-1.058337e+01,39004,0,...,5,0,0,0,0,2,6,1,1,1
20,69961,0.0,2013-03-12,562.0,-27,613.0,39.322307,-6.850262e+00,36315,0,...,5,0,0,2,2,2,6,1,1,1
21,55083,0.0,2011-03-07,524.0,1674,2396.0,34.943620,-9.352515e+00,18590,0,...,5,0,0,1,1,1,1,1,1,1
22,8691,0.0,2013-02-04,1891.0,1087,2396.0,31.046088,-5.054196e+00,40965,0,...,3,1,4,2,2,4,2,1,3,3
23,30331,0.0,2013-02-09,NaN,1441,NaN,34.621048,-5.165926e+00,29152,0,...,3,6,2,0,0,2,6,1,1,1
24,70970,0.0,2012-10-07,848.0,0,2396.0,33.722359,-3.047122e+00,18175,0,...,5,0,0,2,2,4,2,1,0,0
25,61136,200.0,2011-02-23,2046.0,1726,2396.0,34.929592,-9.152872e+00,45433,0,...,2,0,0,2,2,1,1,1,1,1
26,28799,0.0,2013-02-18,1317.0,986,2396.0,35.424443,-1.057969e+01,20256,0,...,5,0,0,0,0,8,0,2,1,1
27,46825,0.0,2011-04-10,326.0,0,1111.0,35.894877,-6.147522e+00,442,0,...,1,5,3,0,0,2,6,1,4,1
28,44718,0.0,2013-02-04,1837.0,0,2396.0,0.000000,-2.000000e-08,40629,0,...,0,2,3,2,2,4,2,1,0,0
29,37350,0.0,2013-02-20,1331.0,1309,1149.0,36.291761,-5.242313e+00,6916,0,...,5,0,0,3,3,6,4,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14820,52228,0.0,2013-01-27,1096.0,265,2089.0,38.504640,-1.016990e+01,5288,0,...,5,0,0,3,3,6,4,2,1,1
14821,70038,5.0,2013-03-29,828.0,1322,2396.0,37.261731,-3.235687e+00,36025,0,...,1,0,0,2,2,8,0,2,1,1
14822,25901,50.0,2013-01-22,754.0,640,1525.0,39.297410,-1.092504e+01,4555,0,...,1,0,0,1,1,1,1,1,1,1
14823,21131,0.0,2011-04-03,NaN,0,NaN,33.918953,-9.298466e+00,31495,0,...,3,0,0,2,2,1,1,1,1,1
14824,26580,0.0,2011-04-20,798.0,574,2165.0,37.070462,-6.575076e+00,9918,0,...,5,0,0,1,1,4,2,1,0,0
14825,66059,0.0,2013-02-02,144.0,331,1850.0,38.761961,-1.091314e+01,17726,0,...,5,0,0,1,1,2,6,1,0,0
14826,32944,0.0,2012-10-24,1624.0,0,1565.0,32.243937,-3.311621e+00,36859,0,...,3,0,0,2,2,4,2,1,0,0
14827,13686,0.0,2011-07-23,55.0,0,31.0,32.985694,-2.734208e+00,8440,0,...,4,0,0,2,2,4,2,1,0,0
14828,8471,50.0,2011-02-20,2135.0,78,2403.0,39.254272,-7.060921e+00,36826,0,...,1,5,3,2,2,2,6,1,3,3
14829,19620,0.0,2013-01-03,952.0,836,1123.0,35.227320,-1.103905e+01,28526,0,...,3,0,0,2,2,1,1,1,1,1
14830,74162,0.0,2013-03-19,72.0,1651,572.0,37.962243,-4.494348e+00,29827,0,...,5,0,0,1,1,1,1,1,1,1
14831,37994,0.0,2012-10-26,55.0,0,2396.0,0.000000,-2.000000e-08,7477,0,...,5,5,3,2,2,4,2,1,0,0
14832,71151,0.0,2013-03-25,2118.0,1393,787.0,36.930169,-3.255077e+00,956,0,...,3,4,5,2,2,2,6,1,1,1
14833,45017,1000.0,2011-03-05,2118.0,1729,1361.0,34.302104,-9.455737e+00,18590,0,...,4,0,0,2,2,1,1,1,1,1
14834,12592,0.0,2011-03-27,404.0,0,2396.0,35.840727,-4.633272e+00,14716,0,...,2,0,0,1,1,1,1,1,1,1
14835,58693,0.0,2013-01-25,358.0,0,2396.0,32.442886,-3.644662e+00,15790,0,...,3,0,0,2,2,4,2,1,0,0
14836,57539,0.0,2011-03-18,60.0,-7,2181.0,39.140091,-7.477423e+00,45254,0,...,5,0,0,2,2,4,2,1,0,0
14837,71252,500.0,2013-02-10,1891.0,1241,639.0,30.114667,-4.162845e+00,1651,0,...,4,0,0,2,2,2,6,1,0,0
14838,7869,3000.0,2011-03-11,2118.0,2046,1361.0,34.345525,-9.547077e+00,18590,0,...,4,0,0,2,2,1,1,1,1,1
14839,57316,0.0,2011-03-11,1541.0,347,242.0,38.613415,-4.815222e+00,24044,0,...,5,0,0,1,1,1,1,1,1,1
14840,59757,0.0,2013-02-24,1549.0,1291,1764.0,35.345384,-9.831170e+00,42538,0,...,5,0,0,2,2,8,0,2,1,1
14841,64579,0.0,2012-10-26,1837.0,0,2396.0,0.000000,-2.000000e-08,44292,0,...,3,0,0,2,2,4,2,1,0,0
14842,57731,600.0,2013-01-27,1328.0,808,2396.0,29.740224,-4.882705e+00,34397,0,...,2,0,0,2,2,8,0,2,4,1
14843,65541,0.0,2013-02-04,1993.0,1641,2102.0,29.768139,-4.480618e+00,13178,0,...,5,0,0,2,2,1,1,1,3,3
14844,68174,0.0,2012-11-07,295.0,0,2396.0,34.096878,-3.079689e+00,31443,0,...,6,0,0,2,2,4,2,1,0,0
14845,39307,0.0,2011-02-24,842.0,34,891.0,38.852669,-6.582841e+00,40883,0,...,5,0,0,2,2,8,0,2,1,1
14846,18990,1000.0,2011-03-21,1571.0,0,2254.0,37.451633,-5.350428e+00,39851,0,...,4,5,3,1,1,4,2,1,0,0
14847,28749,0.0,2013-03-04,NaN,1476,NaN,34.739804,-4.585587e+00,17676,0,...,5,0,0,1,1,7,5,2,1,1
14848,33492,0.0,2013-02-18,1317.0,998,2396.0,35.432732,-1.058416e+01,2125,0,...,5,0,0,1,1,8,0,2,1,1
14849,68707,0.0,2013-02-13,952.0,481,1123.0,34.765054,-1.122601e+01,9776,0,...,5,0,0,0,0,1,1,1,1,1

In [7]:
df.columns

Index([u'id', u'amount_tsh', u'date_recorded', u'funder', u'gps_height',
       u'installer', u'longitude', u'latitude', u'wpt_name', u'num_private',
       u'basin', u'subvillage', u'region', u'region_code', u'district_code',
       u'lga', u'ward', u'population', u'public_meeting', u'recorded_by',
       u'scheme_management', u'scheme_name', u'permit', u'construction_year',
       u'extraction_type', u'extraction_type_group', u'extraction_type_class',
       u'management', u'management_group', u'payment', u'payment_type',
       u'water_quality', u'quality_group', u'quantity', u'quantity_group',
       u'source', u'source_type', u'source_class', u'waterpoint_type',
       u'waterpoint_type_group'],
      dtype='object')

In [13]:

df.dtypes

df['id'].value_counts(normalize=True)

4094     0.000067
39654    0.000067
35588    0.000067
58105    0.000067
27384    0.000067
70391    0.000067
33525    0.000067
68340    0.000067
15090    0.000067
41786    0.000067
17133    0.000067
14730    0.000067
68374    0.000067
22727    0.000067
68324    0.000067
14451    0.000067
47842    0.000067
62171    0.000067
5566     0.000067
60120    0.000067
39638    0.000067
66261    0.000067
32935    0.000067
8913     0.000067
49869    0.000067
51916    0.000067
62155    0.000067
57539    0.000067
39686    0.000067
4871     0.000067
           ...
70372    0.000067
54752    0.000067
60951    0.000067
24033    0.000067
17938    0.000067
54800    0.000067
48653    0.000067
69131    0.000067
67082    0.000067
58886    0.000067
3574     0.000067
18215    0.000067
52739    0.000067
54784    0.000067
11775    0.000067
9726     0.000067
15869    0.000067
36347    0.000067
38392    0.000067
28151    0.000067
26102    0.000067
19955    0.000067
50674    0.000067
54768    0.000067
15853    0.000067
1514     0.000067
5608     0.000067
26086    0.000067
19939    0.000067
65536    0.000067
Name: id, Length: 14850, dtype: float64

In [17]:
pd.isnull(df.installer).value_counts()

False    13973
True       877
Name: installer, dtype: int64

In [19]:
type(df)

pandas.core.frame.DataFrame

In [46]:
train_label = pd.read_csv("Training_set_labels.csv")

column_labels = list(train_label.columns.values)
column_labels.remove("id")

for i in column_labels:
    unique_value = train_label[i].unique()
    size=len(unique_value)
    print(size)
    for j in range(size):
        if unique_value[j] != "nan":
            train_label.loc[train_label[i] == unique_value[j], i] = j

train_label.to_csv("train_label_clean.csv", index=False)

train_label

3

          id  status_group
0      69572             0
1       8776             0
2      34310             0
3      67743             1
4      19728             0
5       9944             0
6      19816             1
7      54551             1
8      53934             1
9      46144             0
10     49056             0
11     50409             0
12     36957             0
13     50495             0
14     53752             0
15     61848             0
16     48451             1
17     58155             1
18     34169             2
19     18274             0
20     48375             0
21      6091             0
22     58500             2
23     37862             0
24     51058             0
25     22308             2
26     55012             0
27     20145             0
28     19685             1
29     69124             0
...      ...           ...
59370  14796             0
59371  20387             1
59372  29940             1
59373  15233             0
59374  49651             0
59375  50998             0
59376  34716             1
59377  43986             1
59378  38067             0
59379  58255             0
59380  30647             1
59381  67885             1
59382  47002             1
59383  44616             0
59384  72148             1
59385  34473             0
59386  34952             0
59387  26640             0
59388  72559             0
59389  30410             0
59390  13677             0
59391  44885             1
59392  40607             1
59393  48348             0
59394  11164             1
59395  60739             0
59396  27263             0
59397  37057             0
59398  31282             0
59399  26348             0

[59400 rows x 2 columns]

In [ ]:
train_value = pd.read_csv("Training_values.csv")
test = pd.read_csv('Test_set_values.csv')


column_labels = list(train_value.columns.values)
column_labels.remove("id")
column_labels.remove("amount_tsh")
column_labels.remove("date_recorded")
column_labels.remove("gps_height")
column_labels.remove("longitude")
column_labels.remove("latitude")
column_labels.remove("num_private")
column_labels.remove("region_code")
column_labels.remove("district_code")
column_labels.remove("population")
column_labels.remove("construction_year")

test = test.fillna(test.median())

for i in column_labels:
    unique_value = list(set(np.concatenate((train_value[i].unique(), test[i].unique()))))
    size = len(unique_value)
    print(size)
    for j in range(size):
        if unique_value[j] != "nan":
            test.loc[test[i] == unique_value[j], i] = j

    test = test.fillna(test.median())

    test.to_csv("test.csv", index = False)

test

2141
2411
45684

In [39]:
import os
import matplotlib.pyplot as plt
from sklearn.svm import LinearSVC
from sklearn.grid_search import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.cross_validation import train_test_split

train=pd.read_csv("Training_values.csv")
test=pd.read_csv("Test_set_values")

train

,id,status_group,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,functional,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322e+00,none,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
1,8776,functional,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466e+00,Zahanati,...,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
2,34310,functional,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329e+00,Kwa Mahundi,...,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
3,67743,non functional,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-1.115530e+01,Zahanati Ya Nanyumbu,...,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
4,19728,functional,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359e+00,Shuleni,...,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
5,9944,functional,20.0,2011-03-13,Mkinga Distric Coun,0,DWE,39.172796,-4.765587e+00,Tajiri,...,per bucket,salty,salty,enough,enough,other,other,unknown,communal standpipe multiple,communal standpipe
6,19816,non functional,0.0,2012-10-01,Dwsp,0,DWSP,33.362410,-3.766365e+00,Kwa Ngomho,...,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
7,54551,non functional,0.0,2012-10-09,Rwssp,0,DWE,32.620617,-4.226198e+00,Tushirikiane,...,unknown,milky,milky,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
8,53934,non functional,0.0,2012-11-03,Wateraid,0,Water Aid,32.711100,-5.146712e+00,Kwa Ramadhan Musa,...,never pay,salty,salty,seasonal,seasonal,machine dbh,borehole,groundwater,hand pump,hand pump
9,46144,functional,0.0,2011-08-03,Isingiro Ho,0,Artisan,30.626991,-1.257051e+00,Kwapeto,...,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
10,49056,functional,0.0,2011-02-20,Private,62,Private,39.209518,-7.034139e+00,Mzee Hokororo,...,never pay,salty,salty,enough,enough,machine dbh,borehole,groundwater,other,other
11,50409,functional,200.0,2013-02-18,Danida,1062,DANIDA,35.770258,-1.057417e+01,Kwa Alid Nchimbi,...,on failure,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump
12,36957,functional,0.0,2012-10-14,World Vision,0,World vision,33.798106,-3.290194e+00,Pamba,...,other,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
13,50495,functional,0.0,2013-03-15,Lawatefuka Water Supply,1368,Lawatefuka water sup,37.092574,-3.181783e+00,Kwa John Izack Mmari,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
14,53752,functional,0.0,2012-10-20,Biore,0,WEDECO,34.364073,-3.629333e+00,Mwabasabi,...,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
15,61848,functional,0.0,2011-08-04,Rudep,1645,DWE,31.444121,-8.274962e+00,Kwa Juvenal Ching'Ombe,...,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
16,48451,non functional,500.0,2011-07-04,Unicef,1703,DWE,34.642439,-9.106185e+00,Kwa John Mtenzi,...,monthly,soft,good,dry,dry,river,river/lake,surface,communal standpipe,communal standpipe
17,58155,non functional,0.0,2011-09-04,Unicef,1656,DWE,34.569266,-9.085515e+00,Kwa Rose Chaula,...,on failure,soft,good,dry,dry,river,river/lake,surface,communal standpipe,communal standpipe
18,34169,functional needs repair,0.0,2011-07-22,Hesawa,1162,DWE,32.920154,-1.947868e+00,Ngomee,...,never pay,milky,milky,insufficient,insufficient,spring,spring,groundwater,other,other
19,18274,functional,500.0,2011-02-22,Danida,1763,Danid,34.508967,-9.894412e+00,none,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
20,48375,functional,200.0,2011-02-27,Twe,2216,TWE,34.473430,-9.594990e+00,none,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
21,6091,functional,0.0,2013-02-10,Dwsp,0,DWE,0.000000,-2.000000e-08,Muungano,...,unknown,unknown,unknown,unknown,unknown,shallow well,shallow well,groundwater,hand pump,hand pump
22,58500,functional needs repair,0.0,2011-10-04,Unicef,1510,DWE,34.586901,-8.980014e+00,Shuleni,...,never pay,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
23,37862,functional,500.0,2013-11-03,Isf,672,ISF,37.940029,-4.125595e+00,Kinonga,...,monthly,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
24,51058,functional,0.0,2013-01-21,African Development Bank,1645,DWE,29.747066,-4.495568e+00,Kamsasa,...,unknown,soft,good,enough,enough,spring,spring,groundwater,improved spring,improved spring
25,22308,functional needs repair,0.0,2013-02-25,Government Of Tanzania,1273,DWE,37.422751,-3.317536e+00,Kwa Tukai,...,unknown,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
26,55012,functional,500.0,2013-01-16,Sobodo,200,Kilolo Star,39.370777,-9.942532e+00,Ruhoma Primary School,...,monthly,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
27,20145,functional,0.0,2011-07-11,Hesawa,0,DWE,31.104257,-1.735361e+00,Kwawilliam,...,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
28,19685,non functional,0.0,2013-03-05,Government Of Tanzania,1443,District council,37.611126,-3.263526e+00,Kwa Kibakaya,...,monthly,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
29,69124,functional,0.0,2013-03-16,Lawatefuka Water Supply,1256,Lawatefuka water sup,37.061688,-3.191989e+00,Kwa Willium Kinda,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59370,14796,functional,200.0,2013-01-29,NaN,1154,NaN,30.058731,-4.902633e+00,Village Office,...,monthly,unknown,unknown,unknown,unknown,unknown,other,unknown,other,other
59371,20387,non functional,0.0,2012-10-09,Netherlands,0,DWE,33.586406,-3.040369e+00,Ushirika,...,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
59372,29940,non functional,0.0,2012-10-31,Tlc,0,TLC,32.058548,-5.052101e+00,Kwa Mzee Kamanya,...,per bucket,salty,salty,insufficient,insufficient,shallow well,shallow well,groundwater,other,other
59373,15233,functional,5000.0,2013-01-30,Rudep,1137,Distri,32.125024,-6.784358e+00,Kwa Kadiega,...,annually,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59374,49651,functional,0.0,2012-10-29,Rwssp,0,DWE,0.000000,-2.000000e-08,Nguvu Kazi,...,other,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
59375,50998,functional,40000.0,2011-08-03,Government Of Tanzania,54,DWE,39.046942,-5.061494e+00,Sekondari,...,monthly,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59376,34716,non functional,0.0,2013-02-03,NaN,1581,NaN,34.821039,-5.076258e+00,Nasingo,...,unknown,unknown,unknown,dry,dry,shallow well,shallow well,groundwater,other,other
59377,43986,non functional,0.0,2012-10-23,Government Of Tanzania,0,Government,33.437012,-4.423594e+00,Fpct,...,never pay,soft,good,insufficient,insufficient,dam,dam,surface,communal standpipe multiple,communal standpipe
59378,38067,functional,500.0,2011-03-21,Rc,2101,ACRA,34.620387,-9.358405e+00,Michael Msigwa,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59379,58255,functional,0.0,2011-07-13,Do,0,DO,31.613284,-1.820226e+00,Coffee Plantati,...,never pay,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59380,30647,non functional,6000.0,2011-03-14,Roman,1439,Roman,34.942101,-9.849198e+00,none,...,annually,soft,good,dry,dry,spring,spring,groundwater,communal standpipe,communal standpipe
59381,67885,non functional,0.0,2011-03-16,Mkinga Distric Coun,0,DWE,38.835001,-4.880204e+00,Mijohoroni,...,never pay,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
59382,47002,non functional,6.0,2013-08-03,Ces(gmbh),1383,DWE,37.454759,-3.323599e+00,Kwa Luka Msaki,...,per bucket,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59383,44616,functional,0.0,2013-01-19,World Bank,11,World bank,39.626009,-1.005750e+01,Shuleni,...,unknown,soft,good,enough,enough,rainwater harvesting,rainwater harvesting,surface,hand pump,hand pump
59384,72148,non functional,0.0,2011-07-10,Concern,0,CONCERN,30.667805,-2.483710e+00,Chamkube,...,never pay,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
59385,34473,functional,500.0,2012-11-03,Jaica,1327,JAICA CO,33.951681,-2.021854e+00,Kwa Marunda,...,monthly,salty,salty,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59386,34952,functional,0.0,2011-08-22,Adb,1786,DWE,31.738789,-8.532013e+00,Shule Ya Sekondari Katazi,...,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59387,26640,functional,100.0,2013-03-12,0,25,0,39.176480,-6.957098e+00,Kwa Maliba,...,per bucket,soft,good,enough,enough,machine dbh,borehole,groundwater,communal standpipe,communal standpipe
59388,72559,functional,0.0,2013-01-29,Kidep,1414,DWE,30.692400,-3.593827e+00,Kwa Philipo Kibeba,...,unknown,soft,good,insufficient,insufficient,spring,spring,groundwater,improved spring,improved spring
59389,30410,functional,0.0,2011-08-06,Co,783,DWE,30.646486,-7.365418e+00,Sekondari,...,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59390,13677,functional,0.0,2011-08-04,Rudep,1715,DWE,31.370848,-8.258160e+00,Kwa Mzee Atanas,...,never pay,soft,good,insufficient,insufficient,machine dbh,borehole,groundwater,hand pump,hand pump
59391,44885,non functional,0.0,2013-08-03,Government Of Tanzania,540,Government,38.044070,-4.272218e+00,Kwa,...,never pay,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59392,40607,non functional,0.0,2011-04-15,Government Of Tanzania,0,Government,33.009440,-8.520888e+00,Benard Charles,...,never pay,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59393,48348,functional,0.0,2012-10-27,Private,0,Private,33.866852,-4.287410e+00,Kwa Peter,...,per bucket,soft,good,insufficient,insufficient,dam,dam,surface,other,other
59394,11164,non functional,500.0,2011-03-09,World Bank,351,ML appro,37.634053,-6.124830e+00,Chimeredya,...,monthly,soft,good,enough,enough,machine dbh,borehole,groundwater,communal standpipe,communal standpipe
59395,60739,functional,10.0,2013-05-03,Germany Republi,1210,CES,37.169807,-3.253847e+00,Area Three Namba 27,...,per bucket,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59396,27263,functional,4700.0,2011-05-07,Cefa-njombe,1212,Cefa,35.249991,-9.070629e+00,Kwa Yahona Kuvala,...,annually,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59397,37057,functional,0.0,2011-04-11,NaN,0,NaN,34.017087,-8.750434e+00,Mashine,...,monthly,fluoride,fluoride,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59398,31282,functional,0.0,2011-03-08,Malec,0,Musa,35.861315,-6.378573e+00,Mshoro,...,never pay,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump
59399,26348,functional,0.0,2011-03-23,World Bank,191,World,38.104048,-6.747464e+00,Kwa Mzee Lugawa,...,on failure,salty,salty,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump

In [29]:
pd.isnull(df.num_private).value_counts(normalize=True)

False    1.0
Name: num_private, dtype: float64